name: Deployment
on:
  push:
    branches:
      - main
      - dev

env:
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.nnelrdw.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080

    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Get Code
        uses: actions/checkout@v3
      - name: ğŸ—ƒ Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: ğŸ›  Install dependencies
        run: npm ci
      - name: ğŸƒâ€â™‚ï¸ Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: ğŸš¦ Run tests
        run: npm test
      - name: ğŸ“º Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“º Output information
        run: |        
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"
